### ISSUE TITLE
The document still says 2.3-Draft

### ISSUE THREAD

**Issue by adelton** [commoncriteria/vpnclient#4]
Hello,

both https://commoncriteria.github.io/pp/vpnclient/vpnclient.html and https://commoncriteria.github.io/pp/vpnclient/vpnclient-release.html say

   Version: 2.3-Draft
   2021-08-10

right below the NIAP logo, even if the protection profiled PDF document at https://www.niap-ccevs.org/Profile/Info.cfm?PPID=461&id=461 says Version: 2.3.

Is this just a matter of removing that "-Draft" substring, or is this repo showing some older, draft version?

**Comment by zsmi** [comment]
@adelton The master branch is where all development occurs for the next version of the Protection Profile to be released. Since this is the development branch it will always say -Draft. Probably should update it to say 2.4-Draft instead so as to not confuse people. The https://commoncriteria.github.io page displays the results from building the master branch and since the master branch has -Draft in the version number it will show draft for for both vpnclient.html and vpnclient-release.html. We don't currently build and host any of the other branches. The release branch will not have the -Draft portion in the name.

**Comment by adelton** [comment]
Thanks for the explanation of the purpose of the master branch.

Seeing there is master-2.2 branch there, would it be possible to create master-2.3 and use that as the content for the final non-draft version 2.3?

I don't necessarily need the version 2.3 to be hosted on the github.io page (even if that would be nice as well), I merely need to be able to generate HTML version of the PDF document from https://www.niap-ccevs.org/Profile/Info.cfm?id=461, and this repository seems to be the closest to that goal.

**Comment by zsmi** [comment]
This is actually following an old way of doing things. We're transitioning all of the development to a new model. We will have 3 branches:

master - all development happens here for new versions
release - has only the released versions (on NIAP site)
effective - Latest release plus all of the TDs applied

It looks like someone never tagged the 2.3 version in the source code so we'll have to find what commit was the last one for the release and then tag it. Then you can checkout that tag and build that version of the PP.

**Comment by adelton** [comment]
Sounds like a plan, looking forward to the tag.

Thank you.

**Comment by zsmi** [comment]
@adelton The proper branches and tags should now exist. If you checkout the 2.3 tag the content will match what you linked to but not exactly. It won't match exactly because the version on the NIAP site was from when Word documents were used to write the Protection Profiles so the index will look slightly different and there won't be a version history section.

**Comment by adelton** [comment]
Thank you, @zsmi. The https://commoncriteria.github.io/pp/vpnclient/vpnclient-release.html now has 2.3 content, which is great.

I see that the commit tagged as v2.3 is f814caa of 2021-08-10, the same as the effective branch is currently on, while release branch is a couple of commits further but the edits are minimal in nature. But I wonder if effective should be synced with release (I assume there are not yet any TD's to apply) and if we potentially could also have https://commoncriteria.github.io/pp/vpnclient/vpnclient-effective.html for easy consumption of the effective content.

**Comment by zsmi** [comment]
@adelton Sorry for all the chaos. Things are still evolving. We're trying to make a more standardized process. I fixed the tagging and branches again. From what I'm hearing the effective branches may be going away and there will only be a release and master/development branch. I have a meeting about this today.

**Comment by adelton** [comment]
Hello @zsmi, I notice that https://commoncriteria.github.io/pp/vpnclient/vpnclient-release.html now says 2.4-Draft, even if the https://github.com/commoncriteria/vpnclient/tree/release branch only has.

Could you fix the setup generating HTML to have the vpnclient-release.html match the release content?

**Comment by zsmi** [comment]
Hi @adelton, the pages on https://commoncriteria.github.io always show Protection Profiles built from the master (development) branch of each Protection Profile. As a result you will only see the latest development version of the PP's on https://commoncriteria.github.io. All official releases are stored on NIAP's website (https://www.niap-ccevs.org/Profile/PP.cfm). 

The following page: https://commoncriteria.github.io/pp/vpnclient/vpnclient-release.html is showing what the release version of the currently in development version of the PP will look like.

I hope that helps. We will see about adding a note to the top of the page to make this more clear.

**Comment by adelton** [comment]
So is there some place where the currently-released version (2.3) is published in HTML format, so that people would not need to generate the documents themselves?

Having the future content published is nice but in situation when https://www.niap-ccevs.org/Profile/Info.cfm?PPID=461&id=461 only has PDFs, the currently valid version is sadly very unaccessible.

**Comment by zsmi** [comment]
Normally NIAP posts a PDF and HTML version. I believe the only reason there isn't an HTML version of 2.3 on the website is because 2.3 was published using our old process of developing Protection Profiles and did not contain an HTML version because it was written in Word. The version on Github that's marked as 2.3 is close to what 2.3 is on the NIAP site but not exact. Once version 2.4 of this protection profile is released it will have an HTML version on NIAP's site similar to all of the other PP's that have been developed on Github.

We've contemplated having the release version on the site as well but figured it would create confusion because the only accepted release versions of the PP's come from NIAP's website. The github page was only ever meant to show the currently in development version of each PP.

If you need 2.3 in HTML form and are unable to build it yourself I can build it for you but there's not guarantee for that PP only that it will match what's on NIAP's site. I'm not sure what you're are trying to use the currently released HTML version for so it's hard for me to assist.

**Comment by jmcdaniels** [comment]
Closing this issue you, @adelton please reach out if you need any of the support @zsmi mentioned above.
